// apps/web/src/components/loader.tsx
import { LoaderCircle } from "lucide-react"

export function Loader({
  size = 48,
  children,
}: {
  size?: number
  children?: React.ReactNode
}) {
  return (
    <div className="flex size-full flex-col items-center justify-center gap-3">
      <LoaderCircle
        className="animate-spin text-muted-foreground"
        size={size}
      />
      {children}
    </div>
  )
}

// apps/frontend/src/lib/components/transition/loader.svelte
<script lang="ts">
  import { LoaderCircle } from '@lucide/svelte';
  import type { Snippet } from 'svelte';

  let { size = 48, children }: { size?: number; children?: Snippet } = $props();
</script>

<div class="flex flex-col items-center justify-center w-full h-full gap-3">
  <LoaderCircle class="animate-spin text-muted-foreground" {size} />
  {@render children?.()}
</div>
