// apps/web/src/routes/auth/login.tsx
import { authClient } from "@/lib/auth-client"
import { getSession } from "@/lib/auth-functions"
import { Button } from "@/components/ui/button"
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "@/components/ui/card"
import { createFileRoute, redirect } from "@tanstack/react-router"
import { useState } from "react"

export const Route = createFileRoute("/auth/login")({
  validateSearch: (search) => ({
    error: typeof search.error === "string" ? search.error : undefined,
  }),
  beforeLoad: async () => {
    const session = await getSession()
    if (session) {
      throw redirect({ to: "/home" })
    }
  },
  component: LoginPage,
})

function LoginPage() {
  const search = Route.useSearch()
  const [loading, setLoading] = useState(false)
  const [error, setError] = useState<string | null>(null)

  async function signInWithMicrosoft() {
    setLoading(true)
    setError(null)

    const result = await authClient.signIn.social({
      provider: "microsoft",
      callbackURL: "/home",
      errorCallbackURL: "/auth/login",
    })

    if (result.error) {
      setError(result.error.message ?? "Unable to start Microsoft sign in.")
      setLoading(false)
    }
  }

  return (
    <main className="flex min-h-svh items-center justify-center px-4">
      <Card className="w-full max-w-sm rounded-lg">
        <CardHeader>
          <CardTitle>Sign in</CardTitle>
          <CardDescription>
            Use your Microsoft 365 account to continue.
          </CardDescription>
        </CardHeader>
        <CardContent className="flex flex-col gap-4">
          {search.error === "account" ? (
            <p className="text-sm text-destructive">
              Your account could not be found. Please contact your
              administrator.
            </p>
          ) : null}
          <Button
            className="w-full"
            disabled={loading}
            onClick={signInWithMicrosoft}
          >
            {loading ? "Redirecting..." : "Continue with Microsoft"}
          </Button>
          {error ? <p className="text-sm text-destructive">{error}</p> : null}
        </CardContent>
      </Card>
    </main>
  )
}

// apps/frontend/src/routes/auth/login/+page.svelte
<script lang="ts">
  import { page } from '$app/state';
  import { authClient } from '$lib/auth-client';
  import { Button } from '$lib/components/ui/button';

  let loading = $state(false);
  let error = $state<string | null>(null);

  const accountError = $derived(page.url.searchParams.get('error') === 'account');

  async function signInWithMicrosoft() {
    loading = true;
    error = null;

    const result = await authClient.signIn.social({
      provider: 'microsoft',
      callbackURL: '/home',
      errorCallbackURL: '/auth/login'
    });

    if (result.error) {
      error = result.error.message ?? 'Unable to start Microsoft sign in.';
      loading = false;
    }
  }
</script>

<div class="flex min-h-screen items-center justify-center px-4">
  <div class="flex w-full max-w-sm flex-col gap-5 rounded-lg border bg-background p-6 shadow-sm">
    <div class="space-y-1">
      <h1 class="text-xl font-semibold">Sign in</h1>
      <p class="text-sm text-muted-foreground">Use your Microsoft 365 account to continue.</p>
    </div>

    {#if accountError}
      <p class="text-sm text-destructive">
        Your account could not be found. Please contact your administrator.
      </p>
    {/if}

    <Button class="w-full" onclick={signInWithMicrosoft} disabled={loading}>
      {loading ? 'Redirecting...' : 'Continue with Microsoft'}
    </Button>

    {#if error}
      <p class="text-sm text-destructive">{error}</p>
    {/if}
  </div>
</div>
