// apps/web/src/components/single-select.tsx
import * as React from "react"
import { Check, ChevronDown } from "lucide-react"

import { Button } from "@/components/ui/button"
import {
  Command,
  CommandEmpty,
  CommandGroup,
  CommandInput,
  CommandItem,
  CommandList,
} from "@/components/ui/command"
import {
  Popover,
  PopoverContent,
  PopoverTrigger,
} from "@/components/ui/popover"
import { cn } from "@/lib/utils"

export type SingleSelectOption = {
  value: string
  label: string
  disabled?: boolean
}

export function SingleSelect({
  options,
  value,
  onValueChange,
  placeholder = "Select item...",
  searchPlaceholder = "Search...",
  className,
  disabled,
  onSearch,
  loading,
  disableSort,
}: {
  options: SingleSelectOption[]
  value?: string
  onValueChange: (value: string) => void
  placeholder?: string
  searchPlaceholder?: string
  className?: string
  disabled?: boolean
  onSearch?: (query: string) => void
  loading?: boolean
  disableSort?: boolean
}) {
  const [open, setOpen] = React.useState(false)
  const [search, setSearch] = React.useState("")

  React.useEffect(() => {
    if (!open) setSearch("")
  }, [open])

  React.useEffect(() => {
    onSearch?.(search)
  }, [onSearch, search])

  const filteredOptions = React.useMemo(() => {
    const sort = (items: SingleSelectOption[]) =>
      disableSort ? items : [...items].sort((a, b) => a.label.localeCompare(b.label))

    if (onSearch) return sort(options)

    const current = options.find((option) => option.value === value)
    const matches = sort(options).filter((option) =>
      option.label.toLowerCase().includes(search.toLowerCase()),
    )

    if (!current) return matches
    return [
      current,
      ...matches.filter((option) => option.value !== current.value),
    ]
  }, [disableSort, onSearch, options, search, value])

  const displayText =
    options.find((option) => option.value === value)?.label ?? placeholder

  return (
    <Popover open={open} onOpenChange={setOpen}>
      <PopoverTrigger asChild>
        <Button
          variant="outline"
          role="combobox"
          aria-expanded={open}
          className={cn("w-full justify-between overflow-hidden", className)}
          disabled={disabled}
        >
          <span className="truncate">{displayText}</span>
          <ChevronDown className="ml-2 size-4 shrink-0 opacity-50" />
        </Button>
      </PopoverTrigger>
      <PopoverContent className="w-(--radix-popover-trigger-width) p-0" align="start">
        <Command shouldFilter={false}>
          <CommandInput
            placeholder={searchPlaceholder}
            value={search}
            onValueChange={setSearch}
          />
          <CommandList>
            <CommandEmpty>
              {loading ? "Loading..." : "No results found."}
            </CommandEmpty>
            <CommandGroup className="max-h-64 overflow-auto">
              {loading ? (
                <CommandItem disabled className="cursor-default opacity-50">
                  Loading...
                </CommandItem>
              ) : null}
              {filteredOptions.map((option) => (
                <CommandItem
                  key={option.value}
                  value={option.value}
                  disabled={option.disabled}
                  onSelect={() => {
                    if (option.disabled) return
                    onValueChange(value === option.value ? "" : option.value)
                    setOpen(false)
                  }}
                  className={cn(option.disabled && "cursor-not-allowed opacity-50")}
                >
                  <div
                    className={cn(
                      "mr-2 flex size-4 items-center justify-center rounded-full border border-primary",
                      value === option.value
                        ? "bg-primary text-primary-foreground"
                        : "opacity-50 [&_svg]:invisible",
                    )}
                  >
                    <Check className="size-4" />
                  </div>
                  <span>{option.label}</span>
                </CommandItem>
              ))}
            </CommandGroup>
          </CommandList>
        </Command>
      </PopoverContent>
    </Popover>
  )
}

// apps/frontend/src/lib/components/single-select.svelte
<script lang="ts">
  import { Check, ChevronDown } from '@lucide/svelte';
  import { cn } from '$lib/utils';
  import Button from '$lib/components/ui/button/button.svelte';
  import * as Popover from '$lib/components/ui/popover/index.js';
  import * as Command from '$lib/components/ui/command/index.js';

  type Option = {
    value: string;
    label: string;
    disabled?: boolean;
  };

  let {
    options = [],
    selected = $bindable<string | undefined>(undefined),
    placeholder = 'Select item...',
    searchPlaceholder = 'Search...',
    class: className = '',
    disabled = false,
    onchange = (_selected: string) => {},
    onsearch,
    loading = false,
    disableSort = false,
  }: {
    options: Option[];
    selected?: string;
    placeholder?: string;
    searchPlaceholder?: string;
    class?: string;
    disabled?: boolean;
    onchange?: (selected: string) => void;
    onsearch?: (query: string) => void;
    loading?: boolean;
    disableSort?: boolean;
  } = $props();

  let open = $state(false);
  let search = $state('');

  $effect(() => {
    if (!open) {
      search = '';
    }
  });

  $effect(() => {
    if (onsearch) {
      onsearch(search);
    }
  });

  const filteredOptions = $derived.by(() => {
    const sort = (options: Option[]) => {
      if (disableSort) return options;
      return [...options].sort((a, b) => a.label.localeCompare(b.label));
    };

    if (onsearch) {
      // Server-side filtering — prepend selected item if not in results
      const current = options.find((o) => o.value === selected);
      if (current && !options.some((o) => o.value === selected)) {
        return [current, ...sort(options)];
      }
      return sort(options);
    }
    const current = options.find((o) => o.value === selected);
    return current
      ? [
          current,
          ...sort(options).filter(
            (opt) =>
              opt.value !== selected && opt.label.toLowerCase().includes(search.toLowerCase())
          ),
        ]
      : sort(options).filter((opt) => opt.label.toLowerCase().includes(search.toLowerCase()));
  });

  const selectOption = (value: string) => {
    if (selected === value) {
      selected = '';
    } else {
      selected = value;
    }
    onchange?.(selected);
    open = false;
  };

  const displayText = $derived.by(() => {
    if (!selected) return placeholder;
    const option = options.find((o) => o.value === selected);
    return option?.label ?? placeholder;
  });
</script>

<Popover.Root bind:open>
  <Popover.Trigger>
    {#snippet child({ props })}
      <Button
        {...props}
        variant="outline"
        role="combobox"
        aria-expanded={open}
        class={cn('w-full justify-between overflow-hidden', className)}
        {disabled}
      >
        <span class="truncate">{displayText}</span>
        <ChevronDown class="ml-2 h-4 w-4 shrink-0 opacity-50" />
      </Button>
    {/snippet}
  </Popover.Trigger>
  <Popover.Content class="w-full p-0" align="start">
    <Command.Root shouldFilter={false}>
      <Command.Input placeholder={searchPlaceholder} bind:value={search} />
      <Command.Empty>{loading ? 'Loading...' : 'No results found.'}</Command.Empty>
      <Command.Group class="max-h-64 overflow-auto">
        {#if loading}
          <Command.Item disabled class="opacity-50 cursor-default">Loading...</Command.Item>
        {/if}
        {#each filteredOptions as option}
          <Command.Item
            value={option.value}
            onSelect={() => !option.disabled && selectOption(option.value)}
            disabled={option.disabled}
            class={cn(option.disabled && 'opacity-50 cursor-not-allowed')}
          >
            <div
              class={cn(
                'mr-2 flex h-4 w-4 items-center justify-center rounded-full border border-primary',
                selected === option.value
                  ? 'bg-primary text-primary-foreground'
                  : 'opacity-50 [&_svg]:invisible'
              )}
            >
              <Check class="h-4 w-4" />
            </div>
            <span>{option.label}</span>
          </Command.Item>
        {/each}
      </Command.Group>
    </Command.Root>
  </Popover.Content>
</Popover.Root>
